apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountservice
  namespace: dapreshop
  labels:
    app: accountservice
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: accountservice
  minReadySeconds: 5 
  strategy: 
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1
  template: 
    metadata:
      labels: 
        app: accountservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "accountservice"
        dapr.io/app-port: "80"
    spec:
      containers:
        - name: web
          image: accountservice:debug
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /app
              name: v1
            - mountPath: /remote_debugger:rw
              name: v2
      volumes:
        - name: v1
          hostPath:
            path: /run/desktop/mnt/host/e/dotnet_project/Oxygen-Dapr.EshopSample/Services/AccountService/Host/bin/Debug/net5.0
        - name: v2
          hostPath:
            path: /run/desktop/mnt/host/c/Users/Administrator/vsdbg/vs2017u5
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: dapreshop
  name: accountservice
  annotations: 
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.dapreshop.com
    http:
      paths:
      - path: /
        backend:
          serviceName: accountservice-dapr
          servicePort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobservice
  namespace: dapreshop
  labels:
    app: jobservice
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: jobservice
  minReadySeconds: 5 
  strategy: 
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1 
      maxSurge: 1
  template: 
    metadata:
      labels: 
        app: jobservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "jobservice"
        dapr.io/app-port: "80"
    spec:
      containers:
        - name: web
          image: jobservice:debug
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /app
              name: v1
            - mountPath: /remote_debugger:rw
              name: v2
      volumes:
        - name: v1
          hostPath:
            path: /run/desktop/mnt/host/e/dotnet_project/Oxygen-Dapr.EshopSample/Services/JobService/bin/Debug/net5.0
        - name: v2
          hostPath:
            path: /run/desktop/mnt/host/c/Users/Administrator/vsdbg/vs2017u5