apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: sentinel
  namespace: dapreshop
spec:
  type: middleware.http.sentinel
  version: v1
  metadata:
  - name: appName
    value: "rules"
  - name: logDir
    value: "/tmp"
  - name: flowRules
    value: >-
      []
  - name: circuitbreakerRules
    value: >-
      []
---
apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: sentinelconfig
  namespace: dapreshop
spec:
  httpPipeline:
    handlers:
      - name: sentinel
        type: middleware.http.sentinel