apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: dapreshop-gateway
  namespace: dapreshop
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: apigateway
  namespace: dapreshop
spec:
  hosts:
  - apigateway
  gateways:
  - dapreshop-gateway
  http:
  - route:
    - destination:
        port:
          number: 80
        host: apigateway
    corsPolicy:
      allowOrigins:
      - exact: '*'
      allowMethods:
      - POST
      - GET

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mobiledapreshop
  namespace: dapreshop
spec:
  hosts:
  - "m.dapreshop.com"
  gateways:
  - dapreshop-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: mobilefrontend
    corsPolicy:
      allowOrigins:
      - exact: '*'
      allowMethods:
      - POST
      - GET
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: admindapreshop
  namespace: dapreshop
spec:
  hosts:
  - "admin.dapreshop.com"
  gateways:
  - dapreshop-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: adminfrontend
    corsPolicy:
      allowOrigins:
      - exact: '*'
      allowMethods:
      - POST
      - GET